import { addDays, setHours, setMinutes, startOfToday } from "date-fns"
import { CURRENT_DATA_VERSION } from "./data-version"
import type {
  AnalyticsMetric,
  BrandSettings,
  CalendarEvent,
  HistoryRecord,
  PlatformAccount,
  SystemSettings,
} from "./types"

const today = startOfToday()

export const mockCalendarEvents: CalendarEvent[] = [
  {
    dataVersion: CURRENT_DATA_VERSION,
    id: "evt-1",
    title: "週末セール告知",
    platform: "x",
    tone: "promo",
    content: "【今週末限定】\n\n全品20%OFFのセールを開催中です。\n\n#セール #週末限定",
    scheduledAt: setMinutes(setHours(addDays(today, 1), 10), 0),
    status: "scheduled",
  },
  {
    dataVersion: CURRENT_DATA_VERSION,
    id: "evt-2",
    title: "新商品ティザー",
    platform: "instagram",
    tone: "friendly",
    content: "新コレクションを来週公開します。\n\n#新作 #春コーデ",
    scheduledAt: setMinutes(setHours(addDays(today, 1), 18), 0),
    status: "scheduled",
  },
  {
    dataVersion: CURRENT_DATA_VERSION,
    id: "evt-3",
    title: "会員限定クーポン",
    platform: "line",
    tone: "business",
    content: "LINE友だち限定クーポンを配信予定です。",
    scheduledAt: setMinutes(setHours(addDays(today, 2), 12), 0),
    status: "draft",
  },
  {
    dataVersion: CURRENT_DATA_VERSION,
    id: "evt-4",
    title: "月初キャンペーン",
    platform: "x",
    tone: "friendly",
    content: "新しい月のキャンペーンをお知らせします。",
    scheduledAt: setMinutes(setHours(addDays(today, 3), 9), 0),
    status: "published",
  },
  {
    dataVersion: CURRENT_DATA_VERSION,
    id: "evt-5",
    title: "障害お知らせ",
    platform: "x",
    tone: "business",
    content: "現在、一部機能に障害が発生しています。復旧に向けて対応中です。",
    scheduledAt: setMinutes(setHours(today, 8), 0),
    status: "failed",
  },
]

export const mockHistoryRecords: HistoryRecord[] = [
  {
    dataVersion: CURRENT_DATA_VERSION,
    id: "hist-1",
    platform: "x",
    tone: "friendly",
    targetAudience: "20代女性",
    keywords: "春の新作コレクション、期間限定セール",
    generatedContent:
      "【新商品発売】\n\n春の新作コレクションが登場しました。\n\n#春コーデ #新作 #ファッション",
    createdAt: new Date("2024-01-15T10:30:00"),
    status: "published",
    isFavorite: true,
  },
  {
    dataVersion: CURRENT_DATA_VERSION,
    id: "hist-2",
    platform: "instagram",
    tone: "promo",
    targetAudience: "ファッション好きの女性",
    keywords: "週末限定セール、最大50%OFF",
    generatedContent:
      "週末限定BIG SALEを開催中です。\n\n人気アイテムをお得にチェックできます。\n\n#セール #週末限定 #お得情報",
    createdAt: new Date("2024-01-14T15:20:00"),
    status: "published",
    isFavorite: true,
  },
  {
    dataVersion: CURRENT_DATA_VERSION,
    id: "hist-3",
    platform: "line",
    tone: "business",
    targetAudience: "既存顧客",
    keywords: "会員限定、ポイント2倍キャンペーン",
    generatedContent:
      "いつもご利用いただきありがとうございます。\n\n会員様限定でポイント2倍キャンペーンを開催します。",
    createdAt: new Date("2024-01-13T09:00:00"),
    status: "generated",
    isFavorite: false,
  },
  {
    dataVersion: CURRENT_DATA_VERSION,
    id: "hist-4",
    platform: "x",
    tone: "gyaru",
    targetAudience: "10代から20代前半",
    keywords: "新作コスメ、限定カラー",
    generatedContent: "新作コスメの限定カラーがかわいすぎる件。\n\n#新作コスメ #限定",
    createdAt: new Date("2024-01-12T18:45:00"),
    status: "generated",
    isFavorite: false,
  },
]

export const mockPlatformAccounts: PlatformAccount[] = [
  {
    dataVersion: CURRENT_DATA_VERSION,
    id: "acct-x-main",
    platform: "x",
    displayName: "Sakusaku SNS X",
    status: "connected",
    connectedAt: addDays(today, -20),
    expiresAt: addDays(today, 40),
    credentialsRef: "mock:x:main",
  },
  {
    dataVersion: CURRENT_DATA_VERSION,
    id: "acct-instagram-main",
    platform: "instagram",
    displayName: "Sakusaku SNS Instagram",
    status: "connected",
    connectedAt: addDays(today, -18),
    expiresAt: addDays(today, 22),
    credentialsRef: "mock:instagram:main",
  },
  {
    dataVersion: CURRENT_DATA_VERSION,
    id: "acct-line-main",
    platform: "line",
    displayName: "Sakusaku SNS LINE",
    status: "connected",
    connectedAt: addDays(today, -30),
    expiresAt: addDays(today, 60),
    credentialsRef: "mock:line:main",
  },
]

export const mockAnalyticsMetrics: AnalyticsMetric[] = [
  {
    dataVersion: CURRENT_DATA_VERSION,
    id: "metric-hist-1",
    platform: "x",
    contentId: "hist-1",
    capturedAt: addDays(today, -6),
    impressions: 18400,
    likes: 820,
    comments: 96,
    shares: 145,
    saves: 210,
    clicks: 364,
    engagementRate: 6.91,
  },
  {
    dataVersion: CURRENT_DATA_VERSION,
    id: "metric-hist-2",
    platform: "instagram",
    contentId: "hist-2",
    capturedAt: addDays(today, -5),
    impressions: 24200,
    likes: 1280,
    comments: 142,
    shares: 260,
    saves: 510,
    clicks: 430,
    engagementRate: 9.05,
  },
  {
    dataVersion: CURRENT_DATA_VERSION,
    id: "metric-hist-3",
    platform: "line",
    contentId: "hist-3",
    capturedAt: addDays(today, -4),
    impressions: 9200,
    likes: 220,
    comments: 34,
    shares: 76,
    saves: 40,
    clicks: 310,
    engagementRate: 4.04,
  },
  {
    dataVersion: CURRENT_DATA_VERSION,
    id: "metric-evt-4",
    platform: "x",
    calendarEventId: "evt-4",
    capturedAt: addDays(today, -2),
    impressions: 13800,
    likes: 640,
    comments: 58,
    shares: 112,
    saves: 95,
    clicks: 245,
    engagementRate: 6.56,
  },
]

export const mockBrandSettings: BrandSettings = {
  dataVersion: CURRENT_DATA_VERSION,
  id: "default",
  brandName: "Sakusaku SNS",
  brandBio: "AI-assisted SNS content generation service for marketing teams.",
  targetAudience: "SNS marketers, small business owners, and promotion managers.",
  defaultTones: {
    x: "friendly",
    instagram: "promo",
    line: "business",
  },
  customInstructions:
    "Use concise wording, avoid excessive jargon, and keep the message aligned with the brand voice.",
  firstPerson: "Our team",
  secondPerson: "customers",
  ngWords: ["competitor", "absolute", "100%", "guaranteed"],
  mustHaveWords: ["Sakusaku SNS", "time saving"],
  allowHashtags: true,
  maxHashtags: {
    x: 3,
    instagram: 10,
    line: 0,
  },
  allowEmojis: true,
  contentLength: "medium",
  websiteUrl: "https://example.com/sakusaku-sns",
  contactInfo: "support@example.com (weekdays 10:00-18:00)",
  disclaimer: "Campaigns may end without prior notice.",
}

export const mockSystemSettings: SystemSettings = {
  dataVersion: CURRENT_DATA_VERSION,
  id: "default",
  ai: {
    model: "gpt-4o",
    apiKey: "sk-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
  },
  sns: {
    x: { apiKey: "API_KEY_XXXXXXXX", apiSecret: "API_SECRET_XXXXXXXX", connected: true },
    instagram: { accessToken: "", connected: false },
    line: { channelToken: "", channelSecret: "", connected: false },
  },
  analytics: {
    gaId: "G-XXXXXXXXXX",
  },
  workflow: {
    requireApproval: true,
    autoCleanupDays: "90",
  },
  notifications: {
    emailWeeklyReport: true,
    emailPublishStatus: true,
    inAppToast: true,
  },
}
